security:
    providers:
        custom_user_provider:
            id: App\Security\User\CustomUserProvider
    firewalls:
        main:
            login_link:
                check_route: login_check
                signature_properties: ['id']
                success_handler: App\Security\Authentication\AuthenticationSuccessHandler
                failure_handler: App\Security\Authentication\AuthenticationFailureHandler
                lifetime: 600 #seconds
                max_uses: 1
            logout:
                path: app_logout
                target: home.index
    access_control:
        - { path: '^/dashboard', roles: ROLE_USER }