controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

login_check:
    path: /login_check

app_logout:
    path: /logout
    methods: GET